#!/usr/bin/env bash

_marcli()
{
    local cur script coms opts com
    COMPREPLY=()
    _get_comp_words_by_ref -n : cur words

    # for an alias, get the real script behind it
    if [[ $(type -t ${words[0]}) == "alias" ]]; then
        script=$(alias ${words[0]} | sed -E "s/alias ${words[0]}='(.*)'/\1/")
    else
        script=${words[0]}
    fi

    # lookup for command
    for word in ${words[@]:1}; do
        if [[ $word != -* ]]; then
            com=$word
            break
        fi
    done

    # completing for an option
    if [[ ${cur} == --* ]] ; then
        opts="--help --quiet --verbose --version --ansi --no-ansi --no-interaction"

        case "$com" in
            help)
            opts="${opts} --format --raw"
            ;;
            list)
            opts="${opts} --raw --format"
            ;;
            bool:and)
            opts="${opts} --raw"
            ;;
            bool:not)
            opts="${opts} --raw"
            ;;
            map:read)
            opts="${opts} --raw"
            ;;
            map:write)
            opts="${opts} "
            ;;
            marc:count)
            opts="${opts} "
            ;;
            marc:dump)
            opts="${opts} "
            ;;
            marc:lint)
            opts="${opts} "
            ;;
            marc:split)
            opts="${opts} --output-dir --enum-length --enum-type-chars"
            ;;
            search:duplicates)
            opts="${opts} --raw"
            ;;
            search:find)
            opts="${opts} --tag --ind1 --ind2 --sub --raw --invert"
            ;;
            search:replace)
            opts="${opts} --tag --ind1 --ind2 --sub --raw"
            ;;

        esac

        COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
        __ltrim_colon_completions "$cur"

        return 0;
    fi

    # completing for a command
    if [[ $cur == $com ]]; then
        coms="help list bool:and bool:not map:read map:write marc:count marc:dump marc:lint marc:split search:duplicates search:find search:replace"

        COMPREPLY=($(compgen -W "${coms}" -- ${cur}))
        __ltrim_colon_completions "$cur"

        return 0
    fi
}

complete -o default -F _marcli marcli
